package com.bm.model;

public class AdminBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_book.add_time
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_book.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_book.add_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer addNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_book.id
     *
     * @return the value of admin_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_book.id
     *
     * @param id the value for admin_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_book.add_time
     *
     * @return the value of admin_book.add_time
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_book.add_time
     *
     * @param addTime the value for admin_book.add_time
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_book.book_id
     *
     * @return the value of admin_book.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_book.book_id
     *
     * @param bookId the value for admin_book.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_book.add_number
     *
     * @return the value of admin_book.add_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getAddNumber() {
        return addNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_book.add_number
     *
     * @param addNumber the value for admin_book.add_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAddNumber(Integer addNumber) {
        this.addNumber = addNumber;
    }
}