package com.bm.model;

public class BStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stock.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stock.stock
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stock.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stock.admin_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stock.id
     *
     * @return the value of b_stock.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stock.id
     *
     * @param id the value for b_stock.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stock.stock
     *
     * @return the value of b_stock.stock
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stock.stock
     *
     * @param stock the value for b_stock.stock
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stock.book_id
     *
     * @return the value of b_stock.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stock.book_id
     *
     * @param bookId the value for b_stock.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stock.admin_id
     *
     * @return the value of b_stock.admin_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stock.admin_id
     *
     * @param adminId the value for b_stock.admin_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}