package com.bm.model;

public class TAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_pass
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String adminPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String adminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.job_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String jobNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_name
     *
     * @return the value of t_admin.admin_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_name
     *
     * @param adminName the value for t_admin.admin_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_pass
     *
     * @return the value of t_admin.admin_pass
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getAdminPass() {
        return adminPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_pass
     *
     * @param adminPass the value for t_admin.admin_pass
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAdminPass(String adminPass) {
        this.adminPass = adminPass == null ? null : adminPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_phone
     *
     * @return the value of t_admin.admin_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_phone
     *
     * @param adminPhone the value for t_admin.admin_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.job_number
     *
     * @return the value of t_admin.job_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.job_number
     *
     * @param jobNumber the value for t_admin.job_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber == null ? null : jobNumber.trim();
    }
}