package com.bm.model;

public class TBook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_author
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_ press
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookPress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_createtime
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_ summary
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_remark
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String bookRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.ebook
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String ebook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.sort_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer sortId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.id
     *
     * @return the value of t_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.id
     *
     * @param id the value for t_book.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_number
     *
     * @return the value of t_book.book_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_number
     *
     * @param bookNumber the value for t_book.book_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber == null ? null : bookNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_name
     *
     * @return the value of t_book.book_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_name
     *
     * @param bookName the value for t_book.book_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_author
     *
     * @return the value of t_book.book_author
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_author
     *
     * @param bookAuthor the value for t_book.book_author
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_ press
     *
     * @return the value of t_book.book_ press
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_ press
     *
     * @param bookPress the value for t_book.book_ press
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress == null ? null : bookPress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_createtime
     *
     * @return the value of t_book.book_createtime
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookCreatetime() {
        return bookCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_createtime
     *
     * @param bookCreatetime the value for t_book.book_createtime
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookCreatetime(String bookCreatetime) {
        this.bookCreatetime = bookCreatetime == null ? null : bookCreatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_ summary
     *
     * @return the value of t_book.book_ summary
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookSummary() {
        return bookSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_ summary
     *
     * @param bookSummary the value for t_book.book_ summary
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookSummary(String bookSummary) {
        this.bookSummary = bookSummary == null ? null : bookSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_remark
     *
     * @return the value of t_book.book_remark
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBookRemark() {
        return bookRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_remark
     *
     * @param bookRemark the value for t_book.book_remark
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookRemark(String bookRemark) {
        this.bookRemark = bookRemark == null ? null : bookRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.ebook
     *
     * @return the value of t_book.ebook
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getEbook() {
        return ebook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.ebook
     *
     * @param ebook the value for t_book.ebook
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setEbook(String ebook) {
        this.ebook = ebook == null ? null : ebook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.sort_id
     *
     * @return the value of t_book.sort_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.sort_id
     *
     * @param sortId the value for t_book.sort_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }
}