package com.bm.model;

public class TBorrow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.user_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.borrow_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String borrowDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.also_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String alsoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.is_also
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer isAlso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_borrow.is_continue
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer isContinue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.id
     *
     * @return the value of t_borrow.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.id
     *
     * @param id the value for t_borrow.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.user_id
     *
     * @return the value of t_borrow.user_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.user_id
     *
     * @param userId the value for t_borrow.user_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.book_id
     *
     * @return the value of t_borrow.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.book_id
     *
     * @param bookId the value for t_borrow.book_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.borrow_date
     *
     * @return the value of t_borrow.borrow_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getBorrowDate() {
        return borrowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.borrow_date
     *
     * @param borrowDate the value for t_borrow.borrow_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setBorrowDate(String borrowDate) {
        this.borrowDate = borrowDate == null ? null : borrowDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.also_date
     *
     * @return the value of t_borrow.also_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getAlsoDate() {
        return alsoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.also_date
     *
     * @param alsoDate the value for t_borrow.also_date
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setAlsoDate(String alsoDate) {
        this.alsoDate = alsoDate == null ? null : alsoDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.is_also
     *
     * @return the value of t_borrow.is_also
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getIsAlso() {
        return isAlso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.is_also
     *
     * @param isAlso the value for t_borrow.is_also
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setIsAlso(Integer isAlso) {
        this.isAlso = isAlso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_borrow.is_continue
     *
     * @return the value of t_borrow.is_continue
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getIsContinue() {
        return isContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_borrow.is_continue
     *
     * @param isContinue the value for t_borrow.is_continue
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setIsContinue(Integer isContinue) {
        this.isContinue = isContinue;
    }
}