package com.bm.model;

public class TDiscipline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline.discipline_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer disciplineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_discipline.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer disciplineId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline.id
     *
     * @return the value of t_discipline.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline.id
     *
     * @param id the value for t_discipline.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline.discipline_name
     *
     * @return the value of t_discipline.discipline_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getDisciplineName() {
        return disciplineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline.discipline_name
     *
     * @param disciplineName the value for t_discipline.discipline_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setDisciplineName(Integer disciplineName) {
        this.disciplineName = disciplineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_discipline.discipline_id
     *
     * @return the value of t_discipline.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getDisciplineId() {
        return disciplineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_discipline.discipline_id
     *
     * @param disciplineId the value for t_discipline.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setDisciplineId(Integer disciplineId) {
        this.disciplineId = disciplineId;
    }
}