package com.bm.model;

public class TStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String stuNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.gender
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private String stuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer disciplineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.count
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.is_vip
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    private Integer isVip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_number
     *
     * @return the value of t_student.stu_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getStuNumber() {
        return stuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_number
     *
     * @param stuNumber the value for t_student.stu_number
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setStuNumber(String stuNumber) {
        this.stuNumber = stuNumber == null ? null : stuNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_name
     *
     * @return the value of t_student.stu_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_name
     *
     * @param stuName the value for t_student.stu_name
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.gender
     *
     * @return the value of t_student.gender
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.gender
     *
     * @param gender the value for t_student.gender
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_phone
     *
     * @return the value of t_student.stu_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_phone
     *
     * @param stuPhone the value for t_student.stu_phone
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.discipline_id
     *
     * @return the value of t_student.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getDisciplineId() {
        return disciplineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.discipline_id
     *
     * @param disciplineId the value for t_student.discipline_id
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setDisciplineId(Integer disciplineId) {
        this.disciplineId = disciplineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.count
     *
     * @return the value of t_student.count
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.count
     *
     * @param count the value for t_student.count
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.is_vip
     *
     * @return the value of t_student.is_vip
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public Integer getIsVip() {
        return isVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.is_vip
     *
     * @param isVip the value for t_student.is_vip
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    public void setIsVip(Integer isVip) {
        this.isVip = isVip;
    }
}