package com.bm.dao;

import com.bm.model.AdminBook;
import com.bm.model.AdminBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    long countByExample(AdminBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByExample(AdminBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insert(AdminBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insertSelective(AdminBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    List<AdminBook> selectByExample(AdminBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    AdminBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminBook record, @Param("example") AdminBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExample(@Param("record") AdminBook record, @Param("example") AdminBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKeySelective(AdminBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_book
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKey(AdminBook record);
}