package com.bm.dao;

import com.bm.model.BSort;
import com.bm.model.BSortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    long countByExample(BSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByExample(BSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insert(BSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insertSelective(BSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    List<BSort> selectByExample(BSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    BSort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") BSort record, @Param("example") BSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExample(@Param("record") BSort record, @Param("example") BSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKeySelective(BSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sort
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKey(BSort record);
}