package com.bm.dao;

import com.bm.model.TBorrow;
import com.bm.model.TBorrowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBorrowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    long countByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insert(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insertSelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    List<TBorrow> selectByExample(TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    TBorrow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TBorrow record, @Param("example") TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExample(@Param("record") TBorrow record, @Param("example") TBorrowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKeySelective(TBorrow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_borrow
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKey(TBorrow record);
}