package com.bm.dao;

import com.bm.model.TDiscipline;
import com.bm.model.TDisciplineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDisciplineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    long countByExample(TDisciplineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByExample(TDisciplineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insert(TDiscipline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insertSelective(TDiscipline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    List<TDiscipline> selectByExample(TDisciplineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    TDiscipline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TDiscipline record, @Param("example") TDisciplineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExample(@Param("record") TDiscipline record, @Param("example") TDisciplineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKeySelective(TDiscipline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_discipline
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKey(TDiscipline record);
}