package com.bm.dao;

import com.bm.model.TStudent;
import com.bm.model.TStudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    long countByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int insertSelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    List<TStudent> selectByExample(TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    TStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TStudent record, @Param("example") TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByExample(@Param("record") TStudent record, @Param("example") TStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Mon May 13 14:28:00 CST 2019
     */
    int updateByPrimaryKey(TStudent record);
}